### ISSUE TITLE
[BUG] Invisible armorstand or duplicate player model

### ISSUE THREAD

**Issue by KumaYuki1** [fill1890/FabSit#10]
an invisible armor stand or a player model stays in place when a player disconnects while sitting or laying
![unknown (2)](https://user-images.githubusercontent.com/85951057/181519599-7726de04-e9b0-4f63-84b4-49b18142e5c9.png)
.

**Comment by fill1890** [comment]
Fixed as of 4c3fa2987605658bcd450033995e4d511e7b82ca and release 1.4.2

Thanks for letting me know!
