### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by Klatch13** [fill1890/FabSit#13]
Здравствуйте, я бы хотел поменять язык. Как - мне это сделать?

**Comment by Klatch13** [comment]
@fill1890

**Comment by Klatch13** [comment]
```
{ 
   "action.fabsit.stop_spinning": "Нажмите %s чтобы прекратить вращаться", 
   "action.fabsit.stop_laying": "Нажмите %s чтобы встать", 
   "action.fabsit.stop_sitting": "Нажмите %s чтобы встать", 
  
   "chat.fabsit.sit_air_error": "§4Вы не можете сидеть в пустоте!", 
   "chat.fabsit.pose_air_error": "§4Вы не можете задать позу в пустоте!", 
   "chat.fabsit.sit_spectator_error": "§4Вы не можете сидеть в режиме спектатора", 
   "chat.fabsit.pose_spectator_error": "§4Вы не можете задать позу в режиме спектатора!", 
   "chat.fabsit.sit_state_error": "§4Сейчас нельзя сидеть!", 
   "chat.fabsit.pose_state_error": "§4Сейчас нельзя задать позу!", 
   "chat.fabsit.sit_block_occupied": "На этом блоке уже кто-то сидит!", 
   "chat.fabsit.pose_block_occupied": "На этом блоке уже кто-то задал позу!", 
  
   "chat.fabsit.reload_success": "Конфигурация перезагружена!", 
   "chat.fabsit.reload_error": "Ошибка при перезагрузки конфигурации. Проверьте консоль сервера!", 
  
   "key.fabsit.category": "FabSit", 
   "key.fabsit.sit": "Сидеть", 
   "key.fabsit.lay": "Ползать", 
   "key.fabsit.spin": "Крутиться" 
 }
```
Я перевёл, но не знаю что с этим делать

**Comment by fill1890** [comment]
Added in version 1.5.4, download from [Releases](https://github.com/fill1890/FabSit/releases/tag/v1.5.4)

Client side: install the mod, it should work automatically

Server side: go to `config/fabsit.json` and set `"locale": "en_us"` to `"locale": "ru_RU"`

**Comment by Klatch13** [comment]
Спасибо, я просто устанавливал ru_ru вместо ru_RU и думал почему не работает)

**Comment by Klatch13** [comment]
Так и должно быть?
```
FabSit locale ru_RU not found! Attempting to fall back to en_us...
```

**Comment by fill1890** [comment]
That doesn't look right

Try one of these instead?
[fabsit-1.5.4.zip](https://github.com/fill1890/FabSit/files/9368444/fabsit-1.5.4.zip)

**Comment by Klatch13** [comment]
Спасибо, ошибка пропала

**Comment by Klatch13** [comment]
Оказывается что я подумал что русский перевод был добавлен в версии 1.5.4(я не знал какая у меня версия), а это вы сделали новую версию и добавили мой перевод)
И в итоге я заменил на ru_RU в версии 1.5.3

**Comment by Klatch13** [comment]
Поэтому была ошибка

**Comment by fill1890** [comment]
It actually should've worked with the 1.5.4 update but I think something went wrong when I updated it, I need to change the files on github 

Glad it's working now though :)
